version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "python app/init_db.py && python app/export_data_to_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8080"
